### PR TITLE
Let developer set App Store region for UpdateAvailableInsight

### PR DESCRIPTION
**Pull request by Rubenfer**
Hi,

just started using this library in one of my apps and noticed the report doesn't includes the update available smart insights because my app is only available in Spain and it tries to retrieve metadata from Brazilian App Store.
In this PR I include an optional parameter to set the iTunes region in the create report method. Also including the option to set custom report filename.

Congratulations for this great package.

### CODE REVIEW

**Comment by wetransferplatform** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  View more details on <a href="https://app.bitrise.io/build/70c3fbe2-a0d6-48af-ad6b-dfd5599f506b" target="_blank">Bitrise</a>
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>DiagnosticsTests: Executed 33 tests (0 failed, 0 retried, 0 skipped) in 0.698 seconds</td>
    </tr>
  </tbody>
</table>

### SwiftLint found issues

| Severity | File | Reason |
| -------- | ---- | ------ |
Warning | SmartInsightsReporter.swift:51 | Lines should not have trailing whitespace. (`trailing_whitespace`) |

## Code Coverage Report
| Name | Coverage ||
| --- | --- | --- |

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against ce316993753ff591c1047df454b1a9ff9eda39a6
</p>

**Comment by Rubenfer** [comment]
Good idea! Just updated to use device region.

**Review by AvdLee — APPROVED** [review]
This looks great, thanks a lot!

**Comment by wetransferplatform** [comment]
Congratulations! :tada: This was released as part of [Release 4.3.0](https://github.com/WeTransfer/Diagnostics/releases/tag/4.3.0) :rocket:<p align="right"><i>Generated by <a href="https://github.com/WeTransfer/GitBuddy">GitBuddy</a></i></p>

**Pull request merged**
