### PR TITLE
Use latest write APIs to prevent a crash when storage is full.

### PR DESCRIPTION
**Pull request by AvdLee**
We used to use the `write(_:)` method which has the following documentation:

> This method raises an exception if the file descriptor is closed or is not valid, if the receiver represents an unconnected pipe or socket endpoint, if no free space is left on the file system, or if any other writing error occurs. 

This resulted in several crashes for users which storage was full. With this PR, we fix the crash for users on iOS 13.4 and up which seems good enough for now.

### CODE REVIEW

**Review by kevinrenskers — APPROVED** [review]
Good catch!

**Comment by wetransferplatform** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  **Sources/DiagnosticsLogger.swift#L143** - It is safer to use weak instead of unowned
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  **Sources/DiagnosticsLogger.swift#L186** - It is safer to use weak instead of unowned
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  View more details on <a href="https://app.bitrise.io/build/86eb8f37-941c-4f41-a2b7-2ec5ec3138a1" target="_blank">Bitrise</a>
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Diagnostics: Executed 19 tests, with 0 failures (0 unexpected) in 0.310 (0.629) seconds</td>
    </tr>
  </tbody>
</table>

## Diagnostics.framework: Coverage: 77.11
| File | Coverage ||
| --- | --- | --- |
DiagnosticsLogger.swift | 62.25% | ✅

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against 1baffc901c8d36288108ba93b23c91977cebcec2
</p>

**Review by amirdew — APPROVED** [review]

**Review by kairadiagne — APPROVED** [review]
Looks good!

**Comment by wetransferplatform** [comment]
Congratulations! :tada: This was released as part of [Release 1.9.1](https://github.com/WeTransfer/Diagnostics/releases/tag/1.9.1) :rocket:<p align="right"><i>Generated by <a href="https://github.com/WeTransfer/GitBuddy">GitBuddy</a></i></p>

**Pull request merged**
