### PR TITLE
Add visionOS support

### LINKED ISSUE #162: Add support for visionOS
This SDK would make a ton of sense on visionOS being a brand new wild OS that not all developers have access to.

Thoughts on updating the Package.swift for swift 5.9 and adding visionOS as a platform? You could do the package backwards compatibility for swift 5.5.

### PR DESCRIPTION
**Pull request by Rubenfer**
This Pull Request adds visionOS support while keeping support to Swift 5.5

Fixes #162.

Note that this branch is based on the #169 PR as it should include the privacy manifest file in newly created files to support Swift 5.5.

### CODE REVIEW

**Review by BasThomas — APPROVED** [review]
Nice!

**Review by peagasilva — CHANGES_REQUESTED** [review]
Thank you, @Rubenfer!

Could you please your changes on `master` and remove the privacy manifest changes contained in this branch?

Thanks in advance!

**Review by peagasilva — CHANGES_REQUESTED** [review]
@Rubenfer thanks!

It doesn't seem like the changes were rebased on `master` of have `master` merged in. 

Could you please rebase or merge `master` in this branch? That way, the privacy manifest will be included in the codebase and can be added the `Package.swift` files. 

Thanks in advance!

**Comment by Rubenfer** [comment]
Done, @peagasilva

**Review by peagasilva — APPROVED** [review]
Thanks for going over the feedback, @Rubenfer! 🚀

**Comment by wetransferplatform** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>DiagnosticsTests: Executed 35 tests (0 failed, 0 retried, 0 skipped) in 10.305 seconds</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Slowest test: DiagnosticsReporterTests/testReportingChapters() (2.019s)</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Slowest test: DiagnosticsReporterTests/testWithSmartInsightsProviderReturningExtraInsights() (2.011s)</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Slowest test: DiagnosticsReporterTests/testWithoutProvidingSmartInsightsProvider() (2.008s)</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  View more details on <a href="https://app.bitrise.io/build/113dc796-78fa-4ab4-8908-dbb48505d2bf" target="_blank">Bitrise</a>
  </td>
    </tr>
  </tbody>
</table>

## Code Coverage Report
| Name | Coverage ||
| --- | --- | --- |
Diagnostics | 62.96% | ⚠️

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against b935d47812023fc90c40aaf5f471bdf1b8852a3e
</p>

**Comment by peagasilva** [comment]
@Rubenfer our repository requires signed commits. Would it be possible for you to enable signed commits and recommit them? You can do that by using the following command:

```
 git rebase --exec 'git commit --amend --no-edit -n -S' -i develop
 git push --force
```

You can read more about setting up signed commits [here](https://withblue.ink/2020/05/17/how-and-why-to-sign-git-commits.html).

Thanks in advance!

**Pull request closed without merging**
